// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

type EmDashImage = { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> };

type EmDashFile = { id: string; url?: string; src?: string; filename?: string; mimeType?: string; size?: number; provider?: string; meta?: Record<string, unknown> };

interface SystemFields {
  id: string;
  slug: string | null;
  status: string;
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Profile extends SystemFields {
  title: string;
  role?: string;
  email?: string;
  bio?: PortableTextBlock[];
  available?: boolean;
  cv?: EmDashFile;
  hire_url?: string;
  x_url?: string;
  bento_url?: string;
  github_url?: string;
  linkedin_url?: string;
}

export interface Post extends SystemFields {
  title: string;
  excerpt?: string;
  featured_image?: EmDashImage;
  content?: PortableTextBlock[];
}

export interface Project extends SystemFields {
  title: string;
  summary?: string;
  year?: string;
  live_url?: string;
  github_url?: string;
  featured?: boolean;
  featured_image?: EmDashImage;
  content?: PortableTextBlock[];
}

export interface Stack extends SystemFields {
  title: string;
  category: "Frontend" | "Backend" | "Database" | "DevOps" | "Tools";
  simple_icon?: string;
  icon?: EmDashImage;
}

declare module "emdash" {
  interface EmDashCollections {
    profile: Profile;
    posts: Post;
    projects: Project;
    stack: Stack;
  }
}
